import { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "ar" | "fr" | "de";

export const LANGUAGES: { id: Language; label: string; nativeLabel: string; dir: "ltr" | "rtl" }[] = [
  { id: "en", label: "English", nativeLabel: "English", dir: "ltr" },
  { id: "ar", label: "Arabic", nativeLabel: "العربية", dir: "rtl" },
  { id: "fr", label: "French", nativeLabel: "Français", dir: "ltr" },
  { id: "de", label: "German", nativeLabel: "Deutsch", dir: "ltr" },
];

export const translations = {
  en: {
    nav: {
      dashboard: "Dashboard",
      upload: "Upload",
      settings: "Settings",
      signIn: "Sign in",
      signOut: "Sign out",
      install: "Install App",
      virusTotalProtected: "VirusTotal Protected",
    },
    home: {
      title: "Dashboard",
      subtitle: "Manage your Minecraft mods and maps",
      javaFiles: "Java Files",
      bedrockFiles: "Bedrock Files",
      clean: "Clean",
      malicious: "Malicious",
      javaEdition: "Java Edition",
      bedrockEdition: "Bedrock Edition",
      mods: "Mods",
      maps: "Maps",
      noMods: "No mods yet",
      noMaps: "No maps yet",
      stored: "stored",
      awaitingScan: "awaiting scan",
      files: "files",
      searchPlaceholder: "Search by name or ID…",
      noResults: "No results match your search",
    },
    upload: {
      title: "Upload File",
      subtitle: "Select an edition and file type, then upload directly from your device.",
      stepEdition: "1 — Edition",
      stepType: "2 — File Type",
      stepFile: "3 — Select File",
      stepCustomId: "4 — Unique ID",
      stepCustomIdDesc: "A unique identifier for your mod/map (e.g. my-cool-mod)",
      customIdPlaceholder: "my-cool-mod",
      customIdHint: "Lowercase letters, numbers, and hyphens only · 3–50 chars",
      customIdTaken: "This ID is already taken, please choose another",
      customIdInvalid: "Only lowercase letters, numbers, and hyphens (3–50 chars)",
      stepDescription: "5 — Description",
      stepDescriptionOptional: "(optional)",
      stepImages: "6 — Screenshots / Images",
      stepImagesOptional: "(optional, up to 10)",
      javaEdition: "Java Edition",
      bedrockEdition: "Bedrock Edition",
      mod: "Mod",
      map: "Map",
      modSub: "Game modification",
      mapSub: "World or adventure map",
      dropHint: "Tap to browse files",
      maxSize: "Max 500 MB",
      descriptionPlaceholder: "Describe what this mod or map does...",
      addImages: "Add image",
      uploadButton: "Upload",
      uploadingButton: "Uploading...",
      uploadedButton: "Uploaded",
      uploadSuccess: "Uploaded successfully. File is being scanned in the background.",
      withImages: "Upload with",
      image: "image",
      images: "images",
    },
    settings: {
      title: "Settings",
      subtitle: "Customize appearance",
      saved: "Saved",
      themeSection: "Theme",
      displaySection: "Display",
      languageSection: "Language",
      darkMode: "Dark Mode",
      darkModeDesc: "Use dark background across the interface",
      languageLabel: "Interface Language",
      languageDesc: "Choose the language used throughout the app",
    },
    profile: {
      title: "Profile",
      subtitle: "Edit your personal info",
      saved: "Saved",
      uploading: "Uploading...",
      changePhoto: "Change photo",
      displayName: "Display name",
      displayNamePlaceholder: "Your name as shown to others",
      usernameLabel: "Username",
      usernamePlaceholder: "my_username",
      usernameTaken: "❌ This username is taken, try another",
      usernameAvailable: "✅ Username available",
      usernameHint: "3–20 characters: letters, numbers, _ or -",
      profileUrlLabel: "Your page link: /u/",
      bioLabel: "Bio (optional)",
      bioPlaceholder: "Write something about yourself...",
      saveButton: "Save changes",
      saving: "Saving...",
    },
    userProfile: {
      userNotFound: "User not found",
      noAccount: "No account exists with this handle",
      backToHome: "← Back to home",
      uploadedFiles: "Uploaded files",
      filesUploaded: "files uploaded",
      noFilesYet: "No files yet",
      notScanned: "Not scanned",
    },
    scan: {
      pending: "Pending",
      scanning: "Scanning",
      clean: "Clean",
      malicious: "Malicious",
      unverified: "Unverified",
      skipped: "Not Scanned (small file)",
    },
    fileDetail: {
      notFound: "File not found",
      back: "Back",
      download: "Download",
      scan: "Scan with VirusTotal",
      scanning: "Scanning…",
      viewReport: "View full report",
      detectionRatio: "Detection ratio",
      scanEngine: "Scan engine",
      scanDetails: "Details",
      uploadedAt: "Uploaded",
      fileSize: "File size",
      edition: "Edition",
      type: "Type",
      description: "Description",
      images: "Images",
      deleteFile: "Delete File",
    },
    common: {
      loading: "Loading…",
      error: "Error",
      notFound: "Not Found",
    },
  },
  ar: {
    nav: {
      dashboard: "لوحة التحكم",
      upload: "رفع ملف",
      settings: "الإعدادات",
      signIn: "تسجيل الدخول",
      signOut: "تسجيل الخروج",
      install: "تثبيت التطبيق",
      virusTotalProtected: "محمي بـ VirusTotal",
    },
    home: {
      title: "لوحة التحكم",
      subtitle: "إدارة مودات وخرائط ماينكرافت",
      javaFiles: "ملفات جافا",
      bedrockFiles: "ملفات بيدروك",
      clean: "نظيف",
      malicious: "خطير",
      javaEdition: "إصدار جافا",
      bedrockEdition: "إصدار بيدروك",
      mods: "المودات",
      maps: "الخرائط",
      noMods: "لا توجد مودات بعد",
      noMaps: "لا توجد خرائط بعد",
      stored: "مُخزَّن",
      awaitingScan: "بانتظار الفحص",
      files: "ملفات",
      searchPlaceholder: "ابحث بالاسم أو الـ ID…",
      noResults: "لا توجد نتائج تطابق بحثك",
    },
    upload: {
      title: "رفع ملف",
      subtitle: "اختر الإصدار ونوع الملف، ثم ارفعه مباشرة من جهازك.",
      stepEdition: "١ — الإصدار",
      stepType: "٢ — نوع الملف",
      stepFile: "٣ — اختر الملف",
      stepCustomId: "٤ — المعرّف الفريد (ID)",
      stepCustomIdDesc: "معرّف فريد خاص بالمود أو الخريطة (مثال: my-cool-mod)",
      customIdPlaceholder: "my-cool-mod",
      customIdHint: "أحرف صغيرة وأرقام وشرطات فقط · من 3 إلى 50 حرفاً",
      customIdTaken: "هذا الـ ID مستخدم بالفعل، اختر غيره",
      customIdInvalid: "أحرف صغيرة وأرقام وشرطات فقط (3–50 حرفاً)",
      stepDescription: "٥ — الوصف",
      stepDescriptionOptional: "(اختياري)",
      stepImages: "٦ — لقطات الشاشة / الصور",
      stepImagesOptional: "(اختياري، حتى 10 صور)",
      javaEdition: "إصدار جافا",
      bedrockEdition: "إصدار بيدروك",
      mod: "مود",
      map: "خريطة",
      modSub: "تعديل على اللعبة",
      mapSub: "عالم أو خريطة مغامرة",
      dropHint: "اضغط لاختيار الملفات",
      maxSize: "الحد الأقصى 500 ميغابايت",
      descriptionPlaceholder: "صف ما يفعله هذا المود أو الخريطة...",
      addImages: "أضف صورة",
      uploadButton: "رفع",
      uploadingButton: "جارٍ الرفع...",
      uploadedButton: "تم الرفع",
      uploadSuccess: "تم الرفع بنجاح. يتم فحص الملف في الخلفية.",
      withImages: "رفع مع",
      image: "صورة",
      images: "صور",
    },
    settings: {
      title: "الإعدادات",
      subtitle: "تخصيص المظهر",
      saved: "تم الحفظ",
      themeSection: "الثيم",
      displaySection: "العرض",
      languageSection: "اللغة",
      darkMode: "الوضع الداكن",
      darkModeDesc: "استخدام خلفية داكنة في جميع أنحاء الواجهة",
      languageLabel: "لغة الواجهة",
      languageDesc: "اختر اللغة المستخدمة في التطبيق",
    },
    profile: {
      title: "الملف الشخصي",
      subtitle: "تعديل معلوماتك الشخصية",
      saved: "تم الحفظ",
      uploading: "جار الرفع...",
      changePhoto: "تغيير الصورة",
      displayName: "الاسم المعروض",
      displayNamePlaceholder: "اسمك كما يظهر للآخرين",
      usernameLabel: "المعرّف الفريد (Username)",
      usernamePlaceholder: "my_username",
      usernameTaken: "❌ هذا المعرّف محجوز، جرّب آخر",
      usernameAvailable: "✅ المعرّف متاح",
      usernameHint: "3–20 حرف: أحرف إنجليزية، أرقام، _ أو -",
      profileUrlLabel: "رابط صفحتك: /u/",
      bioLabel: "نبذة شخصية (اختياري)",
      bioPlaceholder: "اكتب شيئاً عن نفسك...",
      saveButton: "حفظ التغييرات",
      saving: "جار الحفظ...",
    },
    userProfile: {
      userNotFound: "المستخدم غير موجود",
      noAccount: "لا يوجد حساب بهذا المعرّف",
      backToHome: "← الرجوع للرئيسية",
      uploadedFiles: "الملفات المرفوعة",
      filesUploaded: "ملف مرفوع",
      noFilesYet: "لا توجد ملفات بعد",
      notScanned: "لم يُفحص",
    },
    scan: {
      pending: "بانتظار الفحص",
      scanning: "جارٍ الفحص",
      clean: "نظيف",
      malicious: "خطير",
      unverified: "غير مفحوص",
      skipped: "لم يتم الفحص (ملف صغير)",
    },
    fileDetail: {
      notFound: "الملف غير موجود",
      back: "رجوع",
      download: "تحميل",
      scan: "فحص بـ VirusTotal",
      scanning: "جارٍ الفحص…",
      viewReport: "عرض التقرير الكامل",
      detectionRatio: "نسبة الكشف",
      scanEngine: "محرك الفحص",
      scanDetails: "التفاصيل",
      uploadedAt: "تاريخ الرفع",
      fileSize: "حجم الملف",
      edition: "الإصدار",
      type: "النوع",
      description: "الوصف",
      images: "الصور",
      deleteFile: "حذف الملف",
    },
    common: {
      loading: "جارٍ التحميل…",
      error: "خطأ",
      notFound: "غير موجود",
    },
  },
  fr: {
    nav: {
      dashboard: "Tableau de bord",
      upload: "Téléverser",
      settings: "Paramètres",
      signIn: "Se connecter",
      signOut: "Se déconnecter",
      install: "Installer l'app",
      virusTotalProtected: "Protégé par VirusTotal",
    },
    home: {
      title: "Tableau de bord",
      subtitle: "Gérez vos mods et cartes Minecraft",
      javaFiles: "Fichiers Java",
      bedrockFiles: "Fichiers Bedrock",
      clean: "Sain",
      malicious: "Malveillant",
      javaEdition: "Édition Java",
      bedrockEdition: "Édition Bedrock",
      mods: "Mods",
      maps: "Cartes",
      noMods: "Aucun mod pour l'instant",
      noMaps: "Aucune carte pour l'instant",
      stored: "stocké",
      awaitingScan: "en attente d'analyse",
      files: "fichiers",
      searchPlaceholder: "Rechercher par nom ou ID…",
      noResults: "Aucun résultat ne correspond à votre recherche",
    },
    upload: {
      title: "Téléverser un fichier",
      subtitle: "Sélectionnez une édition et un type de fichier, puis téléversez depuis votre appareil.",
      stepEdition: "1 — Édition",
      stepType: "2 — Type de fichier",
      stepFile: "3 — Sélectionner le fichier",
      stepCustomId: "4 — Identifiant unique",
      stepCustomIdDesc: "Un identifiant unique pour votre mod/carte (ex: my-cool-mod)",
      customIdPlaceholder: "my-cool-mod",
      customIdHint: "Lettres minuscules, chiffres et tirets · 3–50 caractères",
      customIdTaken: "Cet identifiant est déjà pris, veuillez en choisir un autre",
      customIdInvalid: "Lettres minuscules, chiffres et tirets uniquement (3–50 car.)",
      stepDescription: "5 — Description",
      stepDescriptionOptional: "(optionnel)",
      stepImages: "6 — Captures / Images",
      stepImagesOptional: "(optionnel, jusqu'à 10)",
      javaEdition: "Édition Java",
      bedrockEdition: "Édition Bedrock",
      mod: "Mod",
      map: "Carte",
      modSub: "Modification du jeu",
      mapSub: "Monde ou carte d'aventure",
      dropHint: "Appuyez pour parcourir",
      maxSize: "Max 500 Mo",
      descriptionPlaceholder: "Décrivez ce que fait ce mod ou cette carte...",
      addImages: "Ajouter une image",
      uploadButton: "Téléverser",
      uploadingButton: "Téléversement...",
      uploadedButton: "Téléversé",
      uploadSuccess: "Téléversé avec succès. Le fichier est analysé en arrière-plan.",
      withImages: "Téléverser avec",
      image: "image",
      images: "images",
    },
    settings: {
      title: "Paramètres",
      subtitle: "Personnaliser l'apparence",
      saved: "Enregistré",
      themeSection: "Thème",
      displaySection: "Affichage",
      languageSection: "Langue",
      darkMode: "Mode sombre",
      darkModeDesc: "Utiliser un fond sombre dans toute l'interface",
      languageLabel: "Langue de l'interface",
      languageDesc: "Choisissez la langue utilisée dans l'application",
    },
    profile: {
      title: "Profil",
      subtitle: "Modifier vos informations personnelles",
      saved: "Enregistré",
      uploading: "Téléversement...",
      changePhoto: "Changer la photo",
      displayName: "Nom affiché",
      displayNamePlaceholder: "Votre nom tel qu'il apparaît aux autres",
      usernameLabel: "Nom d'utilisateur",
      usernamePlaceholder: "my_username",
      usernameTaken: "❌ Ce nom d'utilisateur est déjà pris, essayez-en un autre",
      usernameAvailable: "✅ Nom d'utilisateur disponible",
      usernameHint: "3–20 caractères : lettres, chiffres, _ ou -",
      profileUrlLabel: "Lien de votre page : /u/",
      bioLabel: "Bio (optionnel)",
      bioPlaceholder: "Écrivez quelque chose à propos de vous...",
      saveButton: "Enregistrer les modifications",
      saving: "Enregistrement...",
    },
    userProfile: {
      userNotFound: "Utilisateur introuvable",
      noAccount: "Aucun compte n'existe avec cet identifiant",
      backToHome: "← Retour à l'accueil",
      uploadedFiles: "Fichiers téléversés",
      filesUploaded: "fichiers téléversés",
      noFilesYet: "Aucun fichier pour l'instant",
      notScanned: "Non analysé",
    },
    scan: {
      pending: "En attente",
      scanning: "Analyse en cours",
      clean: "Sain",
      malicious: "Malveillant",
      unverified: "Non vérifié",
      skipped: "Non analysé (petit fichier)",
    },
    fileDetail: {
      notFound: "Fichier introuvable",
      back: "Retour",
      download: "Télécharger",
      scan: "Analyser avec VirusTotal",
      scanning: "Analyse en cours…",
      viewReport: "Voir le rapport complet",
      detectionRatio: "Taux de détection",
      scanEngine: "Moteur d'analyse",
      scanDetails: "Détails",
      uploadedAt: "Téléversé le",
      fileSize: "Taille du fichier",
      edition: "Édition",
      type: "Type",
      description: "Description",
      images: "Images",
      deleteFile: "Supprimer le fichier",
    },
    common: {
      loading: "Chargement…",
      error: "Erreur",
      notFound: "Introuvable",
    },
  },
  de: {
    nav: {
      dashboard: "Dashboard",
      upload: "Hochladen",
      settings: "Einstellungen",
      signIn: "Anmelden",
      signOut: "Abmelden",
      install: "App installieren",
      virusTotalProtected: "VirusTotal-geschützt",
    },
    home: {
      title: "Dashboard",
      subtitle: "Verwalte deine Minecraft-Mods und -Karten",
      javaFiles: "Java-Dateien",
      bedrockFiles: "Bedrock-Dateien",
      clean: "Sauber",
      malicious: "Schädlich",
      javaEdition: "Java Edition",
      bedrockEdition: "Bedrock Edition",
      mods: "Mods",
      maps: "Karten",
      noMods: "Noch keine Mods",
      noMaps: "Noch keine Karten",
      stored: "gespeichert",
      awaitingScan: "Scan ausstehend",
      files: "Dateien",
      searchPlaceholder: "Nach Name oder ID suchen…",
      noResults: "Keine Ergebnisse für deine Suche",
    },
    upload: {
      title: "Datei hochladen",
      subtitle: "Wähle eine Edition und einen Dateityp, dann lade direkt von deinem Gerät hoch.",
      stepEdition: "1 — Edition",
      stepType: "2 — Dateityp",
      stepFile: "3 — Datei auswählen",
      stepCustomId: "4 — Eindeutige ID",
      stepCustomIdDesc: "Eine eindeutige Kennung für deinen Mod/deine Karte (z.B. my-cool-mod)",
      customIdPlaceholder: "my-cool-mod",
      customIdHint: "Kleinbuchstaben, Ziffern und Bindestriche · 3–50 Zeichen",
      customIdTaken: "Diese ID ist bereits vergeben, bitte wähle eine andere",
      customIdInvalid: "Nur Kleinbuchstaben, Ziffern und Bindestriche (3–50 Zeichen)",
      stepDescription: "5 — Beschreibung",
      stepDescriptionOptional: "(optional)",
      stepImages: "6 — Screenshots / Bilder",
      stepImagesOptional: "(optional, bis zu 10)",
      javaEdition: "Java Edition",
      bedrockEdition: "Bedrock Edition",
      mod: "Mod",
      map: "Karte",
      modSub: "Spielmodifikation",
      mapSub: "Welt oder Abenteuerkarte",
      dropHint: "Zum Durchsuchen tippen",
      maxSize: "Max. 500 MB",
      descriptionPlaceholder: "Beschreibe, was dieser Mod oder diese Karte macht...",
      addImages: "Bild hinzufügen",
      uploadButton: "Hochladen",
      uploadingButton: "Wird hochgeladen...",
      uploadedButton: "Hochgeladen",
      uploadSuccess: "Erfolgreich hochgeladen. Die Datei wird im Hintergrund gescannt.",
      withImages: "Hochladen mit",
      image: "Bild",
      images: "Bilder",
    },
    settings: {
      title: "Einstellungen",
      subtitle: "Erscheinungsbild anpassen",
      saved: "Gespeichert",
      themeSection: "Theme",
      displaySection: "Anzeige",
      languageSection: "Sprache",
      darkMode: "Dunkelmodus",
      darkModeDesc: "Dunklen Hintergrund in der gesamten Oberfläche verwenden",
      languageLabel: "Oberflächensprache",
      languageDesc: "Wähle die in der App verwendete Sprache",
    },
    profile: {
      title: "Profil",
      subtitle: "Bearbeite deine persönlichen Informationen",
      saved: "Gespeichert",
      uploading: "Wird hochgeladen...",
      changePhoto: "Foto ändern",
      displayName: "Anzeigename",
      displayNamePlaceholder: "Dein Name, wie er für andere sichtbar ist",
      usernameLabel: "Benutzername",
      usernamePlaceholder: "my_username",
      usernameTaken: "❌ Dieser Benutzername ist bereits vergeben, wähle einen anderen",
      usernameAvailable: "✅ Benutzername verfügbar",
      usernameHint: "3–20 Zeichen: Buchstaben, Zahlen, _ oder -",
      profileUrlLabel: "Dein Seitenlink: /u/",
      bioLabel: "Bio (optional)",
      bioPlaceholder: "Schreibe etwas über dich...",
      saveButton: "Änderungen speichern",
      saving: "Wird gespeichert...",
    },
    userProfile: {
      userNotFound: "Benutzer nicht gefunden",
      noAccount: "Es existiert kein Konto mit dieser Kennung",
      backToHome: "← Zurück zur Startseite",
      uploadedFiles: "Hochgeladene Dateien",
      filesUploaded: "Dateien hochgeladen",
      noFilesYet: "Noch keine Dateien",
      notScanned: "Nicht gescannt",
    },
    scan: {
      pending: "Ausstehend",
      scanning: "Wird gescannt",
      clean: "Sauber",
      malicious: "Schädlich",
      unverified: "Nicht verifiziert",
      skipped: "Nicht gescannt (kleine Datei)",
    },
    fileDetail: {
      notFound: "Datei nicht gefunden",
      back: "Zurück",
      download: "Herunterladen",
      scan: "Mit VirusTotal scannen",
      scanning: "Wird gescannt…",
      viewReport: "Vollständigen Bericht anzeigen",
      detectionRatio: "Erkennungsrate",
      scanEngine: "Scan-Engine",
      scanDetails: "Details",
      uploadedAt: "Hochgeladen am",
      fileSize: "Dateigröße",
      edition: "Edition",
      type: "Typ",
      description: "Beschreibung",
      images: "Bilder",
      deleteFile: "Datei löschen",
    },
    common: {
      loading: "Wird geladen…",
      error: "Fehler",
      notFound: "Nicht gefunden",
    },
  },
} as const;

export type Translations = (typeof translations)["en"];

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const STORAGE_KEY = "modvault-language";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem(STORAGE_KEY) as Language | null;
    return stored && stored in translations ? stored : "en";
  });

  const langMeta = LANGUAGES.find((l) => l.id === language)!;

  useEffect(() => {
    document.documentElement.dir = langMeta.dir;
    document.documentElement.lang = language;
  }, [language, langMeta.dir]);

  function setLanguage(lang: Language) {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  }

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t: translations[language] as Translations, dir: langMeta.dir }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
